### ISSUE TITLE
Library fails to build with current nightly (rustc 1.27.0-nightly (79252ff4e 2018-04-29))

### ISSUE THREAD

**Issue by Tembocs** [antoyo/tql#33]
I've tried to build the bare library (i.e. on its own) and had a strip of error messages. The message seem to point to the compiler than the library. Any idea how to solve this? I've very little knowledge on Rustc.

```
>>  cargo build
   Compiling unicode-xid v0.1.0
   Compiling winapi v0.3.4
   Compiling proc-macro2 v0.2.3
error[E0433]: failed to resolve. Could not find `TokenNode` in `proc_macro`
  --> C:\Users\tembo\.cargo\registry\src\github.com-1ecc6299db9ec823\proc-macro2-0.2.3\src\unstable.rs:63:33
   |
63 |                     proc_macro::TokenNode::Group(delim, (s.0).0)
   |                                 ^^^^^^^^^ Could not find `TokenNode` in `proc_macro`

error[E0433]: failed to resolve. Could not find `TokenNode` in `proc_macro`
  --> C:\Users\tembo\.cargo\registry\src\github.com-1ecc6299db9ec823\proc-macro2-0.2.3\src\unstable.rs:70:33
   |
70 |                     proc_macro::TokenNode::Op(ch, kind)
   |                                 ^^^^^^^^^ Could not find `TokenNode` in `proc_macro`

error[E0433]: failed to resolve. Could not find `TokenNode` in `proc_macro`
  --> C:\Users\tembo\.cargo\registry\src\github.com-1ecc6299db9ec823\proc-macro2-0.2.3\src\unstable.rs:73:33
   |
73 |                     proc_macro::TokenNode::Term((s.0).0)
   |                                 ^^^^^^^^^ Could not find `TokenNode` in `proc_macro`

error[E0433]: failed to resolve. Could not find `TokenNode` in `proc_macro`
  --> C:\Users\tembo\.cargo\registry\src\github.com-1ecc6299db9ec823\proc-macro2-0.2.3\src\unstable.rs:76:33
   |
76 |                     proc_macro::TokenNode::Literal((l.0).0)
   |                                 ^^^^^^^^^ Could not find `TokenNode` in `proc_macro`

error[E0433]: failed to resolve. Could not find `TokenNode` in `proc_macro`
   --> C:\Users\tembo\.cargo\registry\src\github.com-1ecc6299db9ec823\proc-macro2-0.2.3\src\unstable.rs:124:29
    |
124 |                 proc_macro::TokenNode::Group(delim, s) => {
    |                             ^^^^^^^^^ Could not find `TokenNode` in `proc_macro`

error[E0433]: failed to resolve. Could not find `TokenNode` in `proc_macro`
   --> C:\Users\tembo\.cargo\registry\src\github.com-1ecc6299db9ec823\proc-macro2-0.2.3\src\unstable.rs:133:29
    |
133 |                 proc_macro::TokenNode::Op(ch, kind) => {
    |                             ^^^^^^^^^ Could not find `TokenNode` in `proc_macro`

error[E0433]: failed to resolve. Could not find `TokenNode` in `proc_macro`
   --> C:\Users\tembo\.cargo\registry\src\github.com-1ecc6299db9ec823\proc-macro2-0.2.3\src\unstable.rs:140:29
    |
140 |                 proc_macro::TokenNode::Term(s) => {
    |                             ^^^^^^^^^ Could not find `TokenNode` in `proc_macro`

error[E0433]: failed to resolve. Could not find `TokenNode` in `proc_macro`
   --> C:\Users\tembo\.cargo\registry\src\github.com-1ecc6299db9ec823\proc-macro2-0.2.3\src\unstable.rs:143:29
    |
143 |                 proc_macro::TokenNode::Literal(l) => {
    |                             ^^^^^^^^^ Could not find `TokenNode` in `proc_macro`

error[E0433]: failed to resolve. Could not find `TokenNode` in `proc_macro`
   --> C:\Users\tembo\.cargo\registry\src\github.com-1ecc6299db9ec823\proc-macro2-0.2.3\src\unstable.rs:362:21
    |
362 |         proc_macro::TokenNode::Literal(l) => l,
    |                     ^^^^^^^^^ Could not find `TokenNode` in `proc_macro`

error[E0574]: expected struct, variant or union type, found enum `proc_macro::TokenTree`
  --> C:\Users\tembo\.cargo\registry\src\github.com-1ecc6299db9ec823\proc-macro2-0.2.3\src\unstable.rs:53:21
   |
53 |         TokenStream(proc_macro::TokenTree {
   |                     ^^^^^^^^^^^^^^^^^^^^^ not a struct, variant or union type
help: possible better candidate is found in another module, you can import it into scope
   |
1  | use TokenTree;
   |

error[E0412]: cannot find type `TokenTreeIter` in module `proc_macro`
   --> C:\Users\tembo\.cargo\registry\src\github.com-1ecc6299db9ec823\proc-macro2-0.2.3\src\unstable.rs:102:38
    |
102 | pub struct TokenTreeIter(proc_macro::TokenTreeIter);
    |                                      ^^^^^^^^^^^^^ did you mean `TokenTree`?
help: possible candidates are found in other modules, you can import them into scope
    |
1   | use TokenTreeIter;
    |
1   | use imp::TokenTreeIter;
    |

error[E0599]: no function or associated item named `intern` found for type `proc_macro::Term` in the current scope
   --> C:\Users\tembo\.cargo\registry\src\github.com-1ecc6299db9ec823\proc-macro2-0.2.3\src\unstable.rs:279:14
    |
279 |         Term(proc_macro::Term::intern(string))
    |              ^^^^^^^^^^^^^^^^^^^^^^^^ function or associated item not found in `proc_macro::Term`

error[E0599]: no function or associated item named `float` found for type `proc_macro::Literal` in the current scope
   --> C:\Users\tembo\.cargo\registry\src\github.com-1ecc6299db9ec823\proc-macro2-0.2.3\src\unstable.rs:319:17
    |
319 |         Literal(proc_macro::Literal::float(s))
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^ function or associated item not found in `proc_macro::Literal`

error[E0599]: no function or associated item named `integer` found for type `proc_macro::Literal` in the current scope
   --> C:\Users\tembo\.cargo\registry\src\github.com-1ecc6299db9ec823\proc-macro2-0.2.3\src\unstable.rs:323:17
    |
323 |         Literal(proc_macro::Literal::integer(s.into()))

// some other error messages elided here ...

error: aborting due to 27 previous errors

Some errors occurred: E0412, E0433, E0574, E0599, E0609.
For more information about an error, try `rustc --explain E0412`.
error: Could not compile `proc-macro2`.
```
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by antoyo** [comment]
Thanks for reporting this issue.
I've fixed the compilation on master but it seems some features are not working anymore.
And I'm not even sure it will still work on the next stable Rust.

**Comment by vincascm** [comment]
i use this in Cargo.toml:
```
tql = { version = "0.1", features = ["chrono", "pg"], default-features = false }
```
without default features, may fix it.

**Comment by Tembocs** [comment]
@vincascm, have you managed to use it with SQLite without errors?

**Comment by jq-rs** [comment]
I am seeing the same problem.
